version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directories:
      # find . -name 'package.json' -type f -exec dirname {} \; | sort -u
      - /
      - /benchmarks/basic
      - /examples/basic
      - /examples/with-schema-validation
      - /packages/backend-postgres
      - /packages/cli
      - /packages/openworkflow
    schedule:
      interval: daily
